#!/usr/bin/env node

// This script has to be called with the name of the variable to generate
// A file with name <variable>.html MUST exists
// A file with name <variable>.c will be created

const fs = require('fs');

var content;

const app_name = process.argv[1].split("/").slice(-1).pop();
const filename = process.argv[2];

if (typeof(filename) == "undefined") {
    console.log(`Usage: ${app_name} <var-name>`); 
    process.exit(-1);   
}

console.log(`Processing ${filename}...`);

function readFile(err, data) {
    if (err) {
        throw err;
    }
    content = data;
    processFile();
}

function writeFile(filename, content) {
    fs.writeFile(filename, content, 'utf8', function (err) {
        if (err) throw err;
        console.log(`Saved ${filename}!`);
    });
}

function processFile() {
    content = content
        .replace(/<!-- .* -->/gm,'') // remove comments
        .replace(/\n+/gm,'\n') // remove empty lines
        .replace(/"/gm,'\\"') // escape existing double quotation mark
        .replace(/^[ \t]*(.+)$/gm,'"$1"'); // add quotation marks to create C strings, removing leading spaces or tabs

    // add comments and declaration at the beginning and semi-colon at the end
    content = `// ATTENTION! This file is autogenerated by ${app_name}!
// Do not modify this file.
const char ${filename}[] PROGMEM = ${content};`

    writeFile(`${filename}.c`, content);
}


// First I want to read the file
fs.readFile(`./${filename}.html`, 'utf8', readFile);

